# -*- coding: utf-8 -*-
"""
This module contains all the custom exceptions used by the Sankhya SDK.
"""

from .base import IXmlServiceException, SankhyaException, ServiceRequestGeneralException
from .intermediate import (
    ServiceRequestInvalidOperationException,
    ServiceRequestTemporarilyException,
)
from .operations import (
    ConfirmInvoiceException,
    InvalidServiceQueryOptionsException,
    InvalidServiceRequestOperationException,
    MarkAsPaymentPaidException,
    MissingSerializerHelperEntityException,
    NoItemsConfirmInvoiceException,
    OpenFileException,
    PagedRequestException,
    RemoveInvoiceException,
    ServiceResponseUnexpectedElementException,
    UnlinkShippingException,
)
from .service_request import (
    ServiceRequestAttributeException,
    ServiceRequestBusinessRuleRestrictionException,
    ServiceRequestCanceledQueryException,
    ServiceRequestExternalException,
    ServiceRequestFileNotFoundException,
    ServiceRequestForeignKeyException,
    ServiceRequestInaccessibleException,
    ServiceRequestInvalidExpressionException,
    ServiceRequestInvalidSubqueryException,
    ServiceRequestPartnerFiscalClassificationException,
    ServiceRequestPartnerInvalidDocumentLengthException,
    ServiceRequestPartnerStateInscriptionException,
    ServiceRequestPropertyNameException,
    ServiceRequestPropertyValueException,
    ServiceRequestPropertyWidthException,
    ServiceRequestTimeoutException,
)
from .service_request_advanced import (
    ServiceRequestCompetitionException,
    ServiceRequestDeadlockException,
    ServiceRequestDuplicatedDocumentException,
    ServiceRequestFullTransactionLogsException,
    ServiceRequestInvalidRelationException,
    ServiceRequestPaginationException,
    ServiceRequestRepeatedException,
    ServiceRequestTooManyResultsException,
    ServiceRequestUnavailableException,
    ServiceRequestUnbalancedDelimiterException,
    ServiceRequestUnexpectedResultException,
)
from .simple import (
    CanceledOnDemandRequestWrapperException,
    InvalidKeyFileException,
    ServiceRequestExpiredAuthenticationException,
    ServiceRequestInvalidAuthorizationException,
    ServiceRequestInvalidCredentialsException,
    TooInnerLevelsException,
)

__all__ = [
    "IXmlServiceException",
    "SankhyaException",
    "ServiceRequestGeneralException",
    "ServiceRequestInvalidOperationException",
    "ServiceRequestTemporarilyException",
    "ConfirmInvoiceException",
    "InvalidServiceQueryOptionsException",
    "InvalidServiceRequestOperationException",
    "MarkAsPaymentPaidException",
    "MissingSerializerHelperEntityException",
    "NoItemsConfirmInvoiceException",
    "OpenFileException",
    "PagedRequestException",
    "RemoveInvoiceException",
    "ServiceResponseUnexpectedElementException",
    "UnlinkShippingException",
    "ServiceRequestAttributeException",
    "ServiceRequestBusinessRuleRestrictionException",
    "ServiceRequestCanceledQueryException",
    "ServiceRequestExternalException",
    "ServiceRequestFileNotFoundException",
    "ServiceRequestForeignKeyException",
    "ServiceRequestInaccessibleException",
    "ServiceRequestInvalidExpressionException",
    "ServiceRequestInvalidSubqueryException",
    "ServiceRequestPartnerFiscalClassificationException",
    "ServiceRequestPartnerInvalidDocumentLengthException",
    "ServiceRequestPartnerStateInscriptionException",
    "ServiceRequestPropertyNameException",
    "ServiceRequestPropertyValueException",
    "ServiceRequestPropertyWidthException",
    "ServiceRequestTimeoutException",
    "ServiceRequestCompetitionException",
    "ServiceRequestDeadlockException",
    "ServiceRequestDuplicatedDocumentException",
    "ServiceRequestFullTransactionLogsException",
    "ServiceRequestInvalidRelationException",
    "ServiceRequestPaginationException",
    "ServiceRequestRepeatedException",
    "ServiceRequestTooManyResultsException",
    "ServiceRequestUnavailableException",
    "ServiceRequestUnbalancedDelimiterException",
    "ServiceRequestUnexpectedResultException",
    "CanceledOnDemandRequestWrapperException",
    "InvalidKeyFileException",
    "ServiceRequestExpiredAuthenticationException",
    "ServiceRequestInvalidAuthorizationException",
    "ServiceRequestInvalidCredentialsException",
    "TooInnerLevelsException",
]
